/**
 * Claude Design brief (PLAN 4.8, M3, D38): docs/brief/PROMPT-design.md from the live knowledge base.
 *
 *   npm run design:brief
 *
 * The prompt follows the release-wave brief's structure (what this is, brand hook, encodings, interaction, views,
 * design-system deliverables, what to hand back, data contract) and embeds real artifacts: counts, one topic hub, one
 * object page, one source footprint, the BE localization, a one-system excerpt of the galaxy graph. The owner pastes it
 * into Claude Design with the attachments it lists; the output lands in design/ and drives the Astro components.
 */
import { readdirSync } from "node:fs";
import { resolve } from "node:path";
import matter from "gray-matter";
import { exists, listFiles, readJson, readText, writeText } from "../lib/fsx.js";
import { CONTENT_DIR, DATA_DIR, ROOT } from "../lib/paths.js";

const count = (dir: string) => (exists(dir) ? listFiles(dir, ".md").length : 0);
const excerpt = (path: string, lines = 40) => (exists(path) ? readText(path).split("\n").slice(0, lines).join("\n") : "(not available yet)");

export function designBrief(contentDir = CONTENT_DIR, dataDir = DATA_DIR): string {
  const n = {
    topics: count(resolve(contentDir, "topics")), features: count(resolve(contentDir, "features")), objects: count(resolve(contentDir, "objects")),
    localizations: count(resolve(contentDir, "localizations")), videos: count(resolve(contentDir, "videos")), posts: count(resolve(contentDir, "posts")),
    digests: count(resolve(contentDir, "digests")),
  };
  const g = exists(resolve(dataDir, "graph", "summary.json")) ? readJson<any>(resolve(dataDir, "graph", "summary.json")) : { systems: [], nodes: [], edges: [] };
  const sys = "finance";
  const sysNodes = g.nodes.filter((x: any) => x.group === sys).sort((a: any, b: any) => b.weight - a.weight).slice(0, 50);
  const ids = new Set(sysNodes.map((x: any) => x.id));
  const graphExcerpt = { systems: g.systems.filter((s: any) => s.id === sys), nodes: sysNodes, edges: g.edges.filter((e: any) => ids.has(e.s) && ids.has(e.t)) };
  const sources = exists(resolve(contentDir, "posts")) ? readdirSync(resolve(contentDir, "posts")).filter((d) => !d.endsWith(".txt")) : [];
  const fpSource = sources.includes("waldo-be") ? "waldo-be" : sources.sort((a, b) => count(resolve(contentDir, "posts", b)) - count(resolve(contentDir, "posts", a)))[0];
  const fpPosts = fpSource ? listFiles(resolve(contentDir, "posts", fpSource), ".md").map((f) => matter(readText(f)).data).sort((a: any, b: any) => String(a.published_at).localeCompare(String(b.published_at)))
    .map((d: any) => ({ date: String(d.published_at ?? "").slice(0, 10), title: d.title, systems: d.systems ?? [], topics: (d.tags ?? []).slice(0, 4) })) : [];
  const systems = g.systems.map((s: any) => `${s.id} (${s.label})`).join(", ");

  return `# Mega-prompt: "BC Observatory" for Claude Design

> Generated by \`npm run design:brief\` from the live knowledge base on ${new Date().toISOString().slice(0, 10)}. Paste everything below the line into
> Claude Design. Attach: the official Business Central product icon (PNG, unmodified, as brand reference),
> \`design/seed/tokens.release-wave.json\` and \`design/seed/HANDOFF.release-wave.md\` (the previous project's system: start from it,
> do not copy it), and \`data/graph/summary.json\` (the real galaxy graph).

---

## What this is

Design the site for **BC Observatory**: an agent-first, cross-referenced knowledge base of Microsoft Dynamics 365 Business Central,
woven from official docs (Microsoft Learn), the actual source code, the Microsoft 365 roadmap, YouTube sessions and community blogs.
AI agents read it as markdown and JSON first (every page has a markdown twin, \`llms.txt\` per section, an MCP server); people travel
through it like a galaxy. Today it holds ${n.topics} topic hubs, ${n.features} roadmap features, ${n.objects.toLocaleString("en")} AL object pages (BC28-30),
${n.localizations} country localizations, ${n.videos} videos, ${n.posts} community posts and ${n.digests} weekly digests, growing every night.

The person behind it is waldo, a Business Central developer and MVP. The audience: BC developers, consultants, partners, and their AI
agents. Tone: confident, playful, technical; "an observatory you want to spend time in", not a documentation portal. Unofficial: a
visible "unofficial, made by waldo" line, no Microsoft wordmark or Dynamics 365 lockup. Never use em-dashes in copy.

## The metaphor (fixed: it is the data model)

| Galaxy | Data |
|---|---|
| Systems | domains: ${systems} |
| Stars | hubs: topic hubs, roadmap features, AL objects, localizations (brightness = number of sources; colour = official share) |
| Orbiting bodies | evidence attached to a hub: Learn pages, videos (with second), blog posts, roadmap items |
| Constellations | localizations: lines between the W1 objects a country layer changes (BE, NL first) |
| Newly lit stars | content added in the last 7 days (the weekly digest) |
| Flight path | an author's footprint: the hubs a blog or channel touches, in time order |

The home page galaxy exists as a working canvas prototype (systems on a ring, d3-force layout baked at build time, pan/zoom/click). Design
it properly: four zoom levels galaxy -> system -> star -> page, filters by type / tier / country / version, the "newly lit" effect.

## Hard constraints (agent-first)

- Every page has a markdown twin and shows its **trust tier** (official = Microsoft, community = everyone else, mixed = hubs) and its
  **review state** (unreviewed = machine-generated, reviewed = Opus checked it). Design both as first-class, always visible, never alarming.
- Every claim carries evidence (URL, commit, video second, quote under 25 words). Design an **evidence chip** (the most repeated element)
  and an evidence list; timestamps deep-link to YouTube at that second, commits to GitHub.
- Static site on GitHub Pages, ~17k pages, light and dark, 1440 / 1024 / 390 widths, WCAG AA, keyboard navigable. No heavy frameworks.

## Page types to design (real examples below)

1. Home: galaxy + "this week" strip + sections. 2. Topic hub. 3. AL object page (members, events, versions timeline, countries, Learn).
4. Localization page with a diff view against W1. 5. Roadmap feature (status, wave, covering videos and Learn pages). 6. Video page
(chapters, timestamped quotes). 7. Community post. 8. Source footprint / flight path. 9. Weekly digest with deprecation radar.
10. Search results (the MCP and the site share the index).

### Real topic hub (excerpt)

\`\`\`markdown
${excerpt(resolve(contentDir, "topics", "business-central", "business-functionality", "finance.md"), 30)}
\`\`\`

### Real AL object page (excerpt)

\`\`\`markdown
${excerpt(resolve(contentDir, "objects", "table", "18.md"), 70)}
\`\`\`

### Real localization (excerpt)

\`\`\`markdown
${excerpt(resolve(contentDir, "localizations", "be.md"), 45)}
\`\`\`

### Real source footprint (${fpSource ?? "none yet"}, ${fpPosts.length} posts, oldest first)

\`\`\`json
${JSON.stringify(fpPosts.slice(-40), null, 1)}
\`\`\`

### Real galaxy excerpt (system "${sys}", top 50 nodes by weight, layout baked)

\`\`\`json
${JSON.stringify(graphExcerpt)}
\`\`\`

## Design system deliverables

- Tokens for light and dark (background, surface, text, muted, line, link, accent, one colour per galaxy system that works on both
  backgrounds and as small dots, tier and review treatments, status treatments for roadmap features), with contrast ratios.
- Type: one UI face, one mono (ids, commits, timestamps). Sizes for display, headline, body, long-form, caption, chip.
- Components: galaxy (4 zoom levels), star tooltip, evidence chip, evidence list, tier badge, review badge, status badge, object member
  table, version timeline, country diff table, flight path, digest section, search result row, filter bar, breadcrumb, markdown-twin and
  "open in Claude" actions.
- Motion: zoom transitions, hover, newly-lit pulse. Subtle.

## What to hand back

1. Two or three directions for the galaxy as thumbnails with a paragraph each; then the chosen one at full fidelity (desktop, mobile,
   light, dark, four zoom levels).
2. The other page types at medium fidelity, using the real excerpts above.
3. \`design/tokens.json\` and \`design/HANDOFF.md\` in the shape of the attached release-wave files: every value from tokens, component
   names as used above, the canvas/SVG structure you expect for the galaxy, and what is intentionally not pixel-exact.
`;
}

if (process.argv[1]?.endsWith("design-brief.ts")) {
  const path = resolve(ROOT, "docs", "brief", "PROMPT-design.md");
  writeText(path, designBrief());
  console.log(`wrote ${path}`);
}
